name: Code quality

on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: 2.1.4
      - name: Run Biome
        run: biome ci .
